/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123767-g3a1e63e007-20260330"
#endif /* AVUTIL_FFVERSION_H */
